# Deviations from normality

In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import edhec_risk_kit as erk

In [2]:
hfi=erk.get_hfi_returns()

In [3]:
hfi

Convertible Arbitrage  CTA Global  Distressed Securities  \
date                                                                
1997-01                 0.0119      0.0393                 0.0178   
1997-02                 0.0123      0.0298                 0.0122   
1997-03                 0.0078     -0.0021                -0.0012   
1997-04                 0.0086     -0.0170                 0.0030   
1997-05                 0.0156     -0.0015                 0.0233   
...                        ...         ...                    ...   
2018-07                 0.0021     -0.0058                 0.0093   
2018-08                 0.0024      0.0166                 0.0002   
2018-09                 0.0034     -0.0054                 0.0050   
2018-10                -0.0073     -0.0314                -0.0158   
2018-11                -0.0068     -0.0053                -0.0193   

         Emerging Markets  Equity Market Neutral  Event Driven  \
date                                                             
1997-01            0.0791                 0.0189        0.0213   
1997-02            0.0525                 0.0101        0.0084   
1997-03           -0.0120                 0.0016       -0.0023   
1997-04            0.0119                 0.0119       -0.0005   
1997-05            0.0315                 0.0189        0.0346   
...                   ...                    ...           ...   
2018-07            0.0040                -0.0010        0.0055   
2018-08           -0.0277                 0.0004        0.0011   
2018-09           -0.0110                -0.0016        0.0032   
2018-10           -0.0315                -0.0129       -0.0257   
2018-11            0.0120                -0.0211       -0.0034   

         Fixed Income Arbitrage  Global Macro  Long/Short Equity  \
date                                                               
1997-01                  0.0191        0.0573             0.0281   
1997-02                  0.0122        0.0175            -0.0006   
1997-03                  0.0109       -0.0119            -0.0084   
1997-04                  0.0130        0.0172             0.0084   
1997-05                  0.0118        0.0108             0.0394   
...                         ...           ...                ...   
2018-07                  0.0022       -0.0014             0.0067   
2018-08                  0.0017       -0.0007             0.0035   
2018-09                  0.0036        0.0006            -0.0023   
2018-10                 -0.0023       -0.0096            -0.0402   
2018-11                 -0.0067       -0.0087            -0.0044   

         Merger Arbitrage  Relative Value  Short Selling  Funds Of Funds  
date                                                                      
1997-01            0.0150          0.0180        -0.0166          0.0317  
1997-02            0.0034          0.0118         0.0426          0.0106  
1997-03            0.0060          0.0010         0.0778         -0.0077  
1997-04           -0.0001          0.0122        -0.0129          0.0009  
1997-05            0.0197          0.0173        -0.0737          0.0275  
...                   ...             ...            ...             ...  
2018-07           -0.0021          0.0045        -0.0052          0.0018  
2018-08            0.0050         -0.0002        -0.0214          0.0015  
2018-09            0.0028          0.0018         0.0036         -0.0022  
2018-10           -0.0080         -0.0109         0.0237         -0.0269  
2018-11            0.0119         -0.0063        -0.0021         -0.0071  

[263 rows x 13 columns]

In [4]:
pd.concat([hfi.mean(),hfi.median(),hfi.mean()>hfi.median()],axis="columns")

0       1      2
Convertible Arbitrage   0.005508  0.0065  False
CTA Global              0.004074  0.0014   True
Distressed Securities   0.006946  0.0089  False
Emerging Markets        0.006253  0.0096  False
Equity Market Neutral   0.004498  0.0051  False
Event Driven            0.006344  0.0084  False
Fixed Income Arbitrage  0.004365  0.0055  False
Global Macro            0.005403  0.0038   True
Long/Short Equity       0.006331  0.0079  False
Merger Arbitrage        0.005356  0.0060  False
Relative Value          0.005792  0.0067  False
Short Selling          -0.001701 -0.0053   True
Funds Of Funds          0.004262  0.0052  False

In [5]:
from scipy import stats

In [6]:
hfi.skew().sort_values()

Fixed Income Arbitrage   -3.962959
Convertible Arbitrage    -2.654757
Equity Market Neutral    -2.136641
Relative Value           -1.825900
Event Driven             -1.417250
Merger Arbitrage         -1.327668
Distressed Securities    -1.308316
Emerging Markets         -1.173773
Long/Short Equity        -0.392469
Funds Of Funds           -0.363862
CTA Global                0.174697
Short Selling             0.772387
Global Macro              0.988569
dtype: float64

In [7]:
hfi.kurt()

Convertible Arbitrage     20.694912
CTA Global                -0.024781
Distressed Securities      5.007403
Emerging Markets           6.394438
Equity Market Neutral     14.515783
Event Driven               5.156059
Fixed Income Arbitrage    27.382747
Global Macro               2.817691
Long/Short Equity          1.576431
Merger Arbitrage           5.872733
Relative Value             9.320184
Short Selling              3.201032
Funds Of Funds             4.171770
dtype: float64

In [8]:
hfi.shape

(263, 13)

In [9]:
import numpy as np

In [10]:
normal_rets=np.random.normal(0, .1, size=(26300,1))

In [11]:
import scipy

In [12]:
scipy.stats.kurtosis(normal_rets)

array([-0.03662804])

In [13]:
hfi.kurt()

Convertible Arbitrage     20.694912
CTA Global                -0.024781
Distressed Securities      5.007403
Emerging Markets           6.394438
Equity Market Neutral     14.515783
Event Driven               5.156059
Fixed Income Arbitrage    27.382747
Global Macro               2.817691
Long/Short Equity          1.576431
Merger Arbitrage           5.872733
Relative Value             9.320184
Short Selling              3.201032
Funds Of Funds             4.171770
dtype: float64

In [14]:
scipy.stats.jarque_bera(normal_rets)

Jarque_beraResult(statistic=1.4754040585270538, pvalue=0.47821157004282155)

In [15]:
scipy.stats.jarque_bera(hfi)

Jarque_beraResult(statistic=25656.585999171326, pvalue=0.0)

In [16]:
scipy.stats.skew(normal_rets)


array([0.00109123])

In [17]:
scipy.stats.kurtosis(normal_rets)

array([-0.03662804])

In [18]:
scipy.stats.jarque_bera(normal_rets)

Jarque_beraResult(statistic=1.4754040585270538, pvalue=0.47821157004282155)

In [19]:
scipy.stats.jarque_bera(hfi)

Jarque_beraResult(statistic=25656.585999171326, pvalue=0.0)

In [21]:
erk.is_normal(normal_rets)

True

In [22]:
erk.is_normal(hfi)

False

In [25]:
hfi.aggregate(erk.is_normal)

Convertible Arbitrage     False
CTA Global                 True
Distressed Securities     False
Emerging Markets          False
Equity Market Neutral     False
Event Driven              False
Fixed Income Arbitrage    False
Global Macro              False
Long/Short Equity         False
Merger Arbitrage          False
Relative Value            False
Short Selling             False
Funds Of Funds            False
dtype: bool

In [26]:
ffme=erk.get_ffme_returns()


In [27]:
ffme.skew()

SmallCap    4.416709
LargeCap    0.233761
dtype: float64

In [28]:
type(ffme)

pandas.core.frame.DataFrame

In [29]:
ffme.kurt()

SmallCap    44.048575
LargeCap     7.734852
dtype: float64

In [30]:
ffme.aggregate(erk.is_normal)

SmallCap    False
LargeCap    False
dtype: bool